package pheidip.db;

public enum SQLError
{
  UNKNOWN,
  OBJECT_ALREADY_EXISTS,
  TABLE_NOT_FOUND, 
  INVALID_VALUE,
  FOREIGN_KEY_VIOLATION, 
  UNIQUE_VIOLATION, 
  PREPARED_STATEMENT_PARAMETER_NOT_SET;
}
